services:
  vue-game-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      # args:
      #   BUILDKIT_INLINE_CACHE: 1
      # cache_from:
      #   - your-registry/your-vue-app:latest
    container_name: vue-game-container-frontend
    ports:
      - "100:100"
    platform: linux/amd64
  vue-game-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      # args:
      #   BUILDKIT_INLINE_CACHE: 1
      # cache_from:
      #   - your-registry/your-vue-app:latest
    container_name: vue-game-container-backend
    ports:
      - "5001:5001"
    platform: linux/amd64

x-bake:
  target: vue-game
  platforms:
    - linux/amd64
    - linux/arm64
