# Build stage
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
WORKDIR /app
ENV NODE_ENV=production
EXPOSE 100
CMD ["nginx", "-g", "daemon off;"]